### ISSUE TITLE
ImportError: OpenGlCbGetProcAddrFn

### ISSUE THREAD

**Issue by elcoco** [mirkobrombin/Twitz#5]
After installing the twitch package from the arch AUR (1.1.0-1) i get an ImportError:

    $> twitz

    Traceback (most recent call last):
      File "/usr/bin/twitz", line 56, in <module>
        from twitz import main
      File "/usr/share/twitz/twitz/main.py", line 29, in <module>
        from .window import TwitzWindow
      File "/usr/share/twitz/twitz/window.py", line 21, in <module>
        from . import player
      File "/usr/share/twitz/twitz/player.py", line 23, in <module>
        from mpv import MPV, MpvRenderContext, OpenGlCbGetProcAddrFn
    ImportError: cannot import name 'OpenGlCbGetProcAddrFn' from 'mpv' (/usr/lib/python3.10/site-packages/mpv.py)

According to [this](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/README.md#deprecated-opengl-cb-api) page, the opengl_cb interface is not working anymore.

**Comment by mirkobrombin** [comment]
Oh no. I'll check how to fix this

**Comment by autodistries** [comment]
Heya ! I got a similar import error. It's exactly the same case and error as the one presented in this issue, but instead the last error line is: 
`ImportError: cannot import name 'MpvRenderContext' from 'mpv' (/usr/lib/python3.10/site-packages/mpv.py)`
I guess the reason is about the same in both cases

**Comment by mirkobrombin** [comment]
Might be a deprecated API or a missing namespace. Check if libmpv is installed

**Comment by autodistries** [comment]
I'm a bit confused on what I need to ckeck, but the python-mpv package is definietly installed

**Comment by mirkobrombin** [comment]
which distribution is it?

**Comment by autodistries** [comment]
I'm on arch. I got aur/python-mpv installed.
